### ISSUE TITLE
Puppet 4 Conflicts: Reserved Word 'type' is unacceptable as function name and string/integer issues

### ISSUE THREAD

**Issue by lglussen** [pall-valmundsson/puppet-createrepo#17] opened 2015-08-08 05:28 UTC
### 4.x type keyword
The stdlib function `type()` conflicts with the keyword `type` 
> Error: Illegal expression. A Reserved Word 'type' is unacceptable as function name in a Function Call at /etc/puppet/modules/createrepo/manifests/init.pp:96:8

For backwards compatibility, it seems stdlib has created the function `type3x()` to allow code to straddle the 3.x 4.x divide.

https://tickets.puppetlabs.com/browse/MODULES-1473
https://github.com/puppetlabs/puppetlabs-stdlib/pull/382

Changing the function call to `type3x()` solves the issue for me.

---------------------------------------------------------------------------------
### Strings Instead of Integers
I've noticed in puppet 4, I can no longer assign a mode as `mode => 0600`. Such values must now be quoted: `mode => "0600"`.    The `changelog_limit` parameter's default value is raising an error because it is an Integer:
> Error: Evaluation Error: Left match operand must result in a String value. Got an Integer. at /etc/puppet/modules/createrepo/manifests/init.pp:117:16

Adding quotes around the default value fixes the issue: `changelog_limit = "5"`.  Alternatively, as a workaround, configuring the `changelog_limit` avoids the issue by not using the default value. 

Product | Version
-----------|----------
Fedora | 22
Puppet | 4.1.0
puppet-createrepo | 1.0.0
stdlib | 4.7.0

**Comment by lglussen** [comment] 2015-08-08 17:57
I should mention - this issue is against the 1.0.0 release in the puppet forge.  I just tried using the module directly from git and the errors are all gone.

**Comment by pall-valmundsson** [comment] 2015-08-10 16:20
Thanks for a very, very good report. And yes, this was fixed a while ago but not released to the forge, now I'll have to do that.

**Comment by pall-valmundsson** [comment] 2015-08-10 18:35
Version 1.1.0 on the forge.
I'll close this now but if the issue is still there don't hesitate to re-open.
Thanks again.

**Closed by pall-valmundsson** 2015-08-10 18:35 UTC
